version: '3.1'
services: 
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'backend_test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: 
      - "3306:3306"
    volumes:
    - mysqlvol:/var/lib/mysql
  
  mongodb:
    image: mongo:3.6.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: backend_test
    volumes:
    - mongovol:/data/db

  nodejs:
    build:
      context: .
    command: [ "sh", "/target/start.sh" ]      
    depends_on:
      - mysqldb    
    ports:
      - "3000:3000"

volumes:
  mysqlvol:
    external: true
  mongovol:
    external: true

